library(tidyverse)
library(knitr)
library(deSolve)
knitr::opts_chunk$set(
  cache       = TRUE,     # if TRUE knitr will cache the results to reuse in future knits
  fig.width   = 5,       # the width for plots created by code chunk
  fig.height  = 5,       # the height for plots created by code chunk
  fig.align   = 'center', # how to align graphics in the final doc. 'left', 'right', 'center'
  results     = 'asis',   # knitr will pass through results without reformatting them
  echo        = TRUE,     # in FALSE knitr will not display code in the code chunk above it's results
  message     = FALSE,     # if FALSE knitr will not display any messages generated by code
  strip.white = TRUE,     # if FALSE knitr will not remove white spaces at the beg or end of code chunk
  warning     = FALSE)    # if FALSE knitr will not display any warning messages in the final document
