library(tidyverse)
library(knitr)
library(deSolve)
knitr::opts_chunk$set(
  cache       = TRUE,     # if TRUE knitr will cache the results to reuse in future knits
  fig.width   = 5,       # the width for plots created by code chunk
  fig.height  = 5,       # the height for plots created by code chunk
  fig.align   = 'center', # how to align graphics in the final doc. 'left', 'right', 'center'
  results     = 'asis',   # knitr will pass through results without reformatting them
  echo        = TRUE,     # in FALSE knitr will not display code in the code chunk above it's results
  message     = TRUE,     # if FALSE knitr will not display any messages generated by code
  strip.white = TRUE,     # if FALSE knitr will not remove white spaces at the beg or end of code chunk
  warning     = FALSE)    # if FALSE knitr will not display any warning messages in the final document

my_theme <- theme_bw() + theme(legend.position = "bottom")
my_colors_7 <- c('#005a74', '#2b7689', '#4a949d', '#a7a88b', '#e4abd8', '#b45fbb', '#6c2b81')

mylarrow <- arrow(length = unit(0.1, "inches"), ends = "first", type = "closed")
myrarrow <- arrow(length = unit(0.1, "inches"), ends = "last", type = "closed")
